name: Update flake.lock

on:
  schedule:
    - cron: "* * 1 * *"
  workflow_dispatch:

jobs:
  lockfile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-request: write
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "chore(deps): Update flake.lock"
          pr-labels: |
            dependencies
            nix
